#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
CONTAINER_DIR="$SCRIPT_DIR/../"

NAME_PATH="${CONTAINER_DIR}/secrets/username"
PASS_PATH="${CONTAINER_DIR}/secrets/pass"
SHA_KEY_PATH="${CONTAINER_DIR}/secrets/sha"

# Initialize default values
DEFAULT_USERNAME="pykokkos-dev"
DEFAULT_PASSWORD=$(openssl rand -base64 16 | tr -d "=+/" | cut -c1-16)
DEFAULT_SSH_KEY=""

# Create secrets directory if it doesn't exist
mkdir -p "${CONTAINER_DIR}/secrets"

# Initialize secret files with defaults if they don't exist
if [ ! -f "${NAME_PATH}" ]; then
    echo -n "${DEFAULT_USERNAME}" > "${NAME_PATH}"
fi
if [ ! -f "${PASS_PATH}" ]; then
    echo -n "${DEFAULT_PASSWORD}" > "${PASS_PATH}"
fi
if [ ! -f "${SHA_KEY_PATH}" ]; then
    echo -n "${DEFAULT_SSH_KEY}" > "${SHA_KEY_PATH}"
fi

# Secrets input
echo "Secrets initialization. Press 'Enter' to use default values"
read -p "Enter username for dev container [${DEFAULT_USERNAME}]: " dev_name
dev_name=${dev_name:-$DEFAULT_USERNAME}

read -p "Enter password for dev container [randomly generated]: " -s dev_pass
echo
dev_pass=${dev_pass:-$DEFAULT_PASSWORD}

read -p "Enter public SSH key for dev container [none]: " dev_ssh_pubkey
dev_ssh_pubkey=${dev_ssh_pubkey:-$DEFAULT_SSH_KEY}

# Put secrets into secret files
echo -n "${dev_name}" > "${NAME_PATH}"
echo -n "${dev_ssh_pubkey}" > "${SHA_KEY_PATH}"
echo -n "${dev_pass}" > "${PASS_PATH}"

# Output default and autogenerated variables, if some variables are not initialized
echo "Username set: ${dev_name}"
if [ "${dev_pass}" = "${DEFAULT_PASSWORD}" ]; then
    echo "Password set (randomly generated): ${DEFAULT_PASSWORD}"
else
    echo "Password set"
fi
if [ -n "${dev_ssh_pubkey}" ]; then
    echo "SSH key set"
else
    echo "No SSH key provided"
fi

# Set secure permissions (600) of all secrets
chmod 600 "${NAME_PATH}" "${PASS_PATH}" "${SHA_KEY_PATH}" 2>/dev/null || true
echo "Secrets initialization complete"