ARG BASE=nvidia/cuda:11.1-devel-ubuntu20.04
FROM $BASE

ARG ADDITIONAL_PACKAGES

RUN apt-get update && apt-get install -y \
    bc \
    git \
    wget \
    clang \
    gcc-7 \
    g++-7 \
    ccache \
    gfortran-7 \
    python3 \
    python3-pip \
    build-essential \
    $ADDITIONAL_PACKAGES && \
    apt-get --purge autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    python3 -m pip install 'cmake==3.18.4' && \
    update-alternatives --install $(which gcc) gcc $(which gcc-7) 50 --slave $(which g++) g++ $(which g++-7) && \
    update-alternatives --install $(which cc)  cc  $(which gcc) 50 && \
    update-alternatives --install $(which c++) c++ $(which g++) 50

RUN git clone https://github.com/jrmadsen/compile-time-perf.git /tmp/ctp-source && \
    cmake -B /tmp/ctp-build /tmp/ctp-source && \
    cmake --build /tmp/ctp-build --target all && \
    cmake --build /tmp/ctp-build --target install && \
    rm -rf /tmp/ctp-source /tmp/ctp-build
