ARG BASE=nvidia/cuda:10.2-devel
FROM $BASE

ARG ADDITIONAL_PACKAGES

RUN apt-get update && apt-get install -y \
    bc \
    git \
    wget \
    ccache \
    ninja-build \
    python3 \
    python3-pip \
    $ADDITIONAL_PACKAGES \
    && \
    apt-get --purge autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    python3 -m pip install 'cmake==3.18.4'

ENV SYCL_DIR=/opt/sycl
RUN SYCL_VERSION=20210311 && \
    SYCL_URL=https://github.com/intel/llvm/archive/sycl-nightly && \
    SYCL_ARCHIVE=${SYCL_VERSION}.tar.gz && \
    SCRATCH_DIR=/scratch && mkdir -p ${SCRATCH_DIR} && cd ${SCRATCH_DIR} && \
    wget --quiet ${SYCL_URL}/${SYCL_ARCHIVE} && \
    mkdir llvm && \
    tar -xf ${SYCL_ARCHIVE} -C llvm --strip-components=1 && \
    cd llvm && \
    python3 buildbot/configure.py --cuda && \
    python3 buildbot/compile.py && \
    mkdir -p ${SYCL_DIR} && \
    mv ${SCRATCH_DIR}/llvm/build/install/* ${SYCL_DIR} && \
    echo "${SYCL_DIR}/lib" > /etc/ld.so.conf.d/sycl.conf && ldconfig && \
    rm -rf ${SCRATCH_DIR}
ENV PATH=${SYCL_DIR}/bin:$PATH

RUN git clone https://github.com/jrmadsen/compile-time-perf.git /tmp/ctp-source && \
    cmake -B /tmp/ctp-build /tmp/ctp-source && \
    cmake --build /tmp/ctp-build --target all && \
    cmake --build /tmp/ctp-build --target install && \
    rm -rf /tmp/ctp-source /tmp/ctp-build
