[build-system]
requires = [
    "setuptools==84.0.0",
    "wheel==0.48.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "pykokkos"
version = "0.1"
description = "Performance portable Kokkos kernels in Python"
requires-python = ">=3.11,<3.14"

keywords = ["kokkos", "performance", "parallel", "gpu", "cuda", "openmp"]

dependencies = [
    "numpy==2.4.6; python_version < '3.12'",
    "numpy==2.5.3; python_version >= '3.12'",
    "pybind11==3.1.0",
    "pykokkos-base",
]

[project.urls]
Homepage = "https://kokkos.org/pykokkos/index.html"
Repository = "https://github.com/kokkos/pykokkos"
Documentation = "https://kokkos.org/pykokkos/index.html"

[tool.setuptools]
packages = {find = {include = ["pykokkos", "pykokkos.*"]}}
include-package-data = true
