[build-system]
requires = [
    "setuptools == 84.0.0",
    "setuptools_scm == 10.3.4",
    "wheel == 0.48.0",
    "scikit-build == 0.19.0",
    "cmake == 4.4.4",
]
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 88
target-version = ['py310', 'py311', 'py312', 'py313']
include = '\.pyi?'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | external
  | scripts
  | _skbuild
  | __pycache__
  | \.pyc
  | \.pytest_cache
)/
'''
