name: examples/other

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_pykokkos:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.13"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade numpy mypy==1.0.1 cmake pytest pybind11 scikit-build patchelf
      - name: Install pykokkos-base
        run: |
          python install_base.py install -- -DENABLE_LAYOUTS=ON -DENABLE_MEMORY_TRAITS=OFF -DENABLE_VIEW_RANKS=3
      - name: Install pykokkos
        run: |
          python -m pip install .
      - name: mypy check
        run: |
          mypy pykokkos
      - name: Run all other examples
        run: |
          for f in examples/graphs/*.py examples/pykokkos/*.py; do
            echo "Running $f..."
            if [[ "$f" == *"team_thread_mdrange.py" ]]; then
              echo "Skipping $f (requires GPU)"
              continue
            fi
            output=$(python "$f" 2>&1) || {
              if ! echo "$output" | grep -q "ModuleNotFoundError"; then
                echo "$output"
                exit 1
              fi
              echo "Ignoring ModuleNotFoundError in $f"
            }
            echo "$output"
          done
